language: java
jdk:
- oraclejdk7
deploy:
  provider: releases
  api_key:
    secure: AQlFBI/C7aWSS8ZiuPhDbDPXk4ie9uJ+mjOdV6R5mglkNQ4c0bCoqQjOv4JHFcLQY4lKIEvhxzfS5Dt3UMzmKEOYHzPvmtjgV8Q0g+NExowjcUPEc5QSleh66ay/PvJJaH2L/O1q8qXmxqTZeY7+q1tbkvbVWDH3hhzYcWojPXGzSmKgiiNS4+B4bwssJqQaYYebmmNw7Y7AhGP6avwYmFRu6LScHiJnvgHSi3yF9oU8o0Nf5e8NbXIMJR2cTSaEGFe/ie9TPl9slnxFLKlfjfi11JLfoBCx97dSd2SSqa0e+KlXx1y+RRRo3eSQPvyvfquZ967Z/n+zFQUyZ5DTHi45+l3Sr7b/UtwYD+tL80JEKweZbkBdlhtOoFlQFRc02qqmXEN2iXMwTs/YQY4Yyzgv+Tef2qrnZGj4vocHO7WVWVVCmmeVyf6L4vrDG7Y/DMID/Z6z6Tz3NIS8ck2OxiIt7X2rWLFaX4PBNOBRkomwnFtDQHdSJErSyTJAoZtFqEiO9lGti74gAZthzY3PEv3G7mHbZM5CIecacKTbE3a9m+nx1YwvCY7HAXt26Jmq+eRBpWKp9vHmKtGWjabCLS7oScdVB/aHnGiH5mTx9QArfdGl573eP8WMVF3aWwrMN46npvua5lXKuDR6iUB7uOg81tf2/Zi3JlWW+oZHKvI=
  file_glob: true
  file:
  - cli/target/mojito-cli-*.jar
  - webapp/target/mojito-webapp-*.jar
  skip_cleanup: true
  on:
    tags: true
    repo: box/mojito
